### ISSUE TITLE
[Feature request] to_triplets function

### ISSUE THREAD

**Issue by johanmazel** [UnixJunkie/interval-tree#3]
Would it be possible to add a "to_triplets" function ?
This would ease modification after creation.

I know that the original purpose/use case was to to create the tree once and then query it.  But I think this function might be useful in some cases.

**Comment by UnixJunkie** [comment]
That would be welcome.
Do you want to send a pull request ?

**Comment by UnixJunkie** [comment]
When you like a project on github, you can give it a star. ;)

**Comment by UnixJunkie** [comment]
@johanmazel  hello ? Anyone here ?

**Comment by johanmazel** [comment]
Sorry for my rudeness.
I am a bit busy these days. I will try to send a pull request asap, although I cannot promise a date.

**Comment by UnixJunkie** [comment]
Thanks !

**Comment by UnixJunkie** [comment]
merged
